;; Copyright (C) 2014 Jérémy Compostella <jeremy.compostella@gmail.com>

;; This file is NOT part of GNU Emacs.

;; This is free software; you can redistribute it and/or modify it under
;; the terms of the GNU General Public License as published by the Free
;; Software Foundation; either version 2, or (at your option) any later
;; version.

;; This file is distributed in the hope that it will be useful, but
;; WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
;; General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with Emacs; see the file COPYING, or type `C-h C-c'. If not,
;; write to the Free Software Foundation at this address:

;;   Free Software Foundation
;;   51 Franklin Street, Fifth Floor
;;   Boston, MA 02110-1301
;;   USA

(deftheme j2m
  "Face Color theme based on the Tango Palette colors.")

(custom-theme-set-faces
 'j2m
 '(default ((t (:stipple nil :background "black" :foreground "#FFFFFF" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 75 :width normal :foundry "unknown" :family "DejaVu Sans Mono"))))
 '(Man-overstrike ((t (:bold t :weight bold :underline nil))))
 '(Man-reverse ((t (:background "#222244"))))
 '(Man-underline ((t (:underline t))))
 '(android-mode-debug-face ((t (:foreground "ForestGreen"))))
 '(android-mode-error-face ((t (:bold t :foreground "Red" :weight bold))))
 '(android-mode-info-face ((t (:foreground "Gray45"))))
 '(android-mode-verbose-face ((t (:foreground "DodgerBlue"))))
 '(android-mode-warning-face ((t (:foreground "Red"))))
 '(anything-header ((t (:bold t :background "grey15" :foreground "#edd400" :weight bold))))
 '(bold ((t (:bold t :underline nil :weight bold))))
 '(bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
 '(bookmark-menu-heading ((t (:bold t :weight bold :foreground "#8ae234"))))
 '(border ((t (:background "#888a85"))))
 '(buffer-menu-buffer ((t (:bold t :weight bold))))
 '(button ((t (:underline t :foreground "dodger blue"))))
 '(c-annotation-face ((t (:foreground "#8ae234"))))
 '(c-nonbreakable-space-face ((t (:background "#f57900"))))
 '(calendar-today ((t (:underline t))))
 '(change-log-acknowledgment ((t (:foreground "orange3"))))
 '(change-log-conditionals ((t (:foreground "tomato"))))
 '(change-log-date ((t (:italic t :slant italic :foreground "#ad7fa8"))))
 '(change-log-email ((t (:foreground "tomato"))))
 '(change-log-file ((t (:bold t :weight bold :foreground "#edd400"))))
 '(change-log-function ((t (:foreground "tomato"))))
 '(change-log-list ((t (:bold t :weight bold :foreground "#729fcf"))))
 '(change-log-name ((t (:foreground "#8ae234"))))
 '(comint-highlight-input ((t (:italic t :bold t :slant italic :weight bold))))
 '(comint-highlight-prompt ((t (:foreground "#8ae234"))))
 '(compilation-column-number ((t (:foreground "orange3"))))
 '(compilation-error ((t (:bold t :weight bold :foreground "Pink"))))
 '(compilation-info ((t (:bold t :weight bold :foreground "Green1"))))
 '(compilation-line-number ((t (:bold t :weight bold :foreground "#729fcf"))))
 '(compilation-mode-line-exit ((t (:bold t :foreground "ForestGreen" :weight bold))))
 '(compilation-mode-line-fail ((t (:bold t :foreground "Red1" :weight bold))))
 '(compilation-mode-line-run ((t (:bold t :foreground "DarkOrange" :weight bold))))
 '(compilation-warning ((t (:bold t :weight bold :foreground "DarkOrange"))))
 '(completions-annotations ((t (:italic t :slant italic :underline nil))))
 '(completions-common-part ((t (:family "DejaVu Sans Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#FFFFFF" :background "black" :stipple nil :height 75))))
 '(completions-first-difference ((t (:bold t :weight bold :underline nil))))
 '(cursor ((t (:background "yellow"))))
 '(custom-button ((t (:background "grey50" :foreground "black" :box (:line-width 1 :style released-button)))))
 '(custom-button-mouse ((t (:box (:line-width 1 :style released-button) :foreground "black" :background "grey60"))))
 '(custom-button-mouse-pressed-unraised ((t (:foreground "black" :background "grey60"))))
 '(custom-button-mouse-unraised ((t (:foreground "black" :background "grey60"))))
 '(custom-button-pressed ((t (:foreground "black" :background "grey50" :box (:style pressed-button)))))
 '(custom-button-pressed-unraised ((t (:background "grey50" :foreground "violet"))))
 '(custom-button-unraised ((t (:background "grey50" :foreground "black"))))
 '(custom-changed ((t (:background "blue1" :foreground "white"))))
 '(custom-comment ((t (:background "dim gray"))))
 '(custom-comment-tag ((t (:foreground "gray80"))))
 '(custom-documentation ((t (:italic t :slant italic))))
 '(custom-face-tag ((t (:bold t :foreground "#edd400" :weight bold :height 1.1))))
 '(custom-group-subtitle ((t (:bold t :weight bold))))
 '(custom-group-tag ((t (:bold t :foreground "#edd400" :weight bold :height 1.3))))
 '(custom-group-tag-1 ((t (:bold t :family "Sans Serif" :foreground "pink" :weight bold :height 1.2))))
 '(custom-invalid ((t (:background "red1" :foreground "yellow1"))))
 '(custom-link ((t (:underline t :foreground "dodger blue"))))
 '(custom-modified ((t (:background "blue1" :foreground "white"))))
 '(custom-rogue ((t (:background "black" :foreground "pink"))))
 '(custom-saved ((t (:underline t))))
 '(custom-set ((t (:background "white" :foreground "blue1"))))
 '(custom-state ((t (:foreground "lime green"))))
 '(custom-state-face ((t (:foreground "#729fcf"))))
 '(custom-themed ((t (:background "blue1" :foreground "white"))))
 '(custom-variable-button ((t (:box (:line-width 1 :style released-button) :foreground "black" :background "grey50"))))
 '(custom-variable-tag ((t (:bold t :foreground "#edd400" :weight bold :height 1.1))))
 '(custom-visibility ((t (:underline t :foreground "dodger blue" :height 0.8))))
 '(diary ((t (:bold t :foreground "IndianRed" :weight bold))))
 '(diary-anniversary ((t (:bold t :weight bold :foreground "#729fcf"))))
 '(diary-button ((t (nil))))
 '(diary-time ((t (:foreground "tomato"))))
 '(diff-added ((t (:foreground "light green"))))
 '(diff-changed ((t (nil))))
 '(diff-context ((t (nil))))
 '(diff-file-header ((t (:foreground "RoyalBlue1"))))
 '(diff-function ((t (:foreground "#00bbdd"))))
 '(diff-header ((t (:foreground "RoyalBlue1"))))
 '(diff-hunk-header ((t (:foreground "#fbde2d"))))
 '(diff-index ((t (:foreground "RoyalBlue1"))))
 '(diff-indicator-added ((t (:foreground "light green"))))
 '(diff-indicator-changed ((t (nil))))
 '(diff-indicator-removed ((t (:foreground "orange3"))))
 '(diff-nonexistent ((t (:foreground "RoyalBlue1" :strike-through nil))))
 '(diff-refine-added ((t (:background "dark green" :foreground "light green"))))
 '(diff-refine-change ((t (:background "#182042"))))
 '(diff-refine-removed ((t (:background "#aa2222"))))
 '(diff-removed ((t (:foreground "orange3"))))
 '(dired-directory ((t (:bold t :weight bold :foreground "#edd400"))))
 '(dired-flagged ((t (:bold t :weight bold :foreground "Pink"))))
 '(dired-header ((t (:bold t :weight bold :foreground "#8ae234"))))
 '(dired-ignored ((t (:foreground "grey70"))))
 '(dired-mark ((t (:foreground "#8ae234"))))
 '(dired-marked ((t (:bold t :weight bold :foreground "DarkOrange"))))
 '(dired-perm-write ((t (:foreground "orange3"))))
 '(dired-symlink ((t (:bold t :weight bold :foreground "#729fcf"))))
 '(dired-warning ((t (:bold t :weight bold :foreground "#f57900"))))
 '(ecb-default-highlight-face ((t (:background "#729fcf"))))
 '(ecb-tag-header-face ((t (:background "#f57900"))))
 '(ediff-current-diff-A ((t (:background "green" :foreground "firebrick"))))
 '(ediff-current-diff-Ancestor ((t (:background "VioletRed" :foreground "Black"))))
 '(ediff-current-diff-B ((t (:background "Yellow" :foreground "DarkOrchid"))))
 '(ediff-current-diff-C ((t (:background "Pink" :foreground "Navy"))))
 '(ediff-even-diff-A ((t (:background "light grey" :foreground "Black"))))
 '(ediff-even-diff-Ancestor ((t (:background "Grey" :foreground "White"))))
 '(ediff-even-diff-B ((t (:background "Grey" :foreground "White"))))
 '(ediff-even-diff-C ((t (:background "light grey" :foreground "Black"))))
 '(ediff-fine-diff-A ((t (:background "sky blue" :foreground "Navy"))))
 '(ediff-fine-diff-Ancestor ((t (:background "dark green" :foreground "Black"))))
 '(ediff-fine-diff-B ((t (:background "cyan" :foreground "Black"))))
 '(ediff-fine-diff-C ((t (:background "Turquoise" :foreground "Black"))))
 '(ediff-odd-diff-A ((t (:background "Grey" :foreground "White"))))
 '(ediff-odd-diff-Ancestor ((t (:background "gray40" :foreground "cyan3"))))
 '(ediff-odd-diff-B ((t (:background "light grey" :foreground "Black"))))
 '(ediff-odd-diff-C ((t (:background "Grey" :foreground "White"))))
 '(egg-an-tag-mono ((t (:bold t :weight bold :underline nil :foreground "LightGreen"))))
 '(egg-blame ((t (:background "grey15" :foreground "white"))))
 '(egg-blame-culprit ((t (:family "Sans Serif" :background "grey15" :foreground "grey60" :height 1.1))))
 '(egg-blame-subject ((t (:background "grey15" :family "Sans Serif" :foreground "white" :height 1.1))))
 '(egg-branch ((t (:bold t :weight bold :family "Sans Serif" :foreground "Yellow" :height 1.2100000000000002))))
 '(egg-branch-mono ((t (:bold t :weight bold :underline nil :foreground "Yellow"))))
 '(egg-diff-add ((t (:foreground "white"))))
 '(egg-diff-conflict ((t (:foreground "Orange"))))
 '(egg-diff-del ((t (:foreground "OrangeRed"))))
 '(egg-diff-file-header ((t (:bold t :weight bold :family "Sans Serif" :foreground "LightSlateBlue" :height 1.1))))
 '(egg-diff-hunk-header ((t (:background "grey45"))))
 '(egg-diff-none ((t (:foreground "grey70"))))
 '(egg-electrict-choice ((t (:bold t :family "Sans Serif" :foreground "Cyan" :weight bold))))
 '(egg-graph ((t (:foreground "grey30"))))
 '(egg-header ((t (:bold t :family "Sans Serif" :weight bold :height 1.1))))
 '(egg-help-header-1 ((t (:bold t :foreground "SteelBlue" :family "Sans Serif" :weight bold))))
 '(egg-help-header-2 ((t (:family "Sans Serif" :foreground "LightSteelBlue" :height 0.9))))
 '(egg-help-key ((t (:bold t :foreground "Yellow" :underline nil :weight bold :height 0.9))))
 '(egg-log-HEAD ((t (:background "RoyalBlue"))))
 '(egg-log-buffer-mark ((t (:bold t :weight bold :underline nil :foreground "orchid1"))))
 '(egg-remote-mono ((t (:bold t :weight bold :underline nil :foreground "DarkSalmon"))))
 '(egg-section-title ((t (:bold t :weight bold :family "Sans Serif" :foreground "PaleGreen" :height 1.2100000000000002))))
 '(egg-stash-mono ((t (:bold t :weight bold :underline nil :foreground "LightGreen"))))
 '(egg-tag-mono ((t (:bold t :weight bold :underline nil :foreground "SkyBlue"))))
 '(egg-term ((t (:bold t :weight bold :underline nil :foreground "Yellow"))))
 '(egg-text-1 ((t (:foreground "SteelBlue" :family "Sans Serif"))))
 '(egg-text-2 ((t (:foreground "SteelBlue" :family "Sans Serif" :height 1.1))))
 '(egg-text-3 ((t (:foreground "SteelBlue" :family "Sans Serif" :height 1.2))))
 '(egg-text-4 ((t (:foreground "SteelBlue" :family "Sans Serif" :height 1.4))))
 '(egg-text-base ((t (:family "Sans Serif" :foreground "SteelBlue"))))
 '(egg-text-help ((t (:foreground "SteelBlue" :family "Sans Serif" :height 0.8))))
 '(egg-unmerged-diff-file-header ((t (:bold t :family "Sans Serif" :weight bold :foreground "Orange" :height 1.1))))
 '(egg-warning ((t (:bold t :weight bold :underline nil :foreground "Orange"))))
 '(egoge-display-time ((t (:bold t :weight bold :underline nil :foreground "white"))))
 '(eldoc-highlight-function-argument ((t (:bold t :weight bold :underline nil))))
 '(epa-field-body ((t (:italic t :foreground "turquoise" :slant italic))))
 '(epa-field-name ((t (:bold t :foreground "PaleTurquoise" :weight bold))))
 '(epa-mark ((t (:bold t :foreground "orange" :weight bold))))
 '(epa-string ((t (:foreground "lightyellow"))))
 '(epa-validity-disabled ((t (:italic t :slant italic))))
 '(epa-validity-high ((t (:bold t :foreground "PaleTurquoise" :weight bold))))
 '(epa-validity-low ((t (:italic t :slant italic))))
 '(epa-validity-medium ((t (:italic t :foreground "PaleTurquoise" :slant italic))))
 '(error ((t (:bold t :foreground "Red" :weight bold))))
 '(escape-glyph ((t (:foreground "cyan"))))
 '(eshell-ls-clutter-face ((t (:bold t :foreground "DimGray" :weight bold))))
 '(eshell-ls-executable-face ((t (:bold t :foreground "Coral" :weight bold))))
 '(eshell-ls-missing-face ((t (:bold t :foreground "black" :weight bold))))
 '(eshell-ls-special-face ((t (:bold t :foreground "Gold" :weight bold))))
 '(eshell-ls-symlink-face ((t (:bold t :foreground "White" :weight bold))))
 '(ess-jb-comment-face ((t (:italic t :background "#2e3436" :foreground "firebrick" :slant italic))))
 '(ess-jb-h1-face ((t (:foreground "dodger blue" :slant normal :height 1.6))))
 '(ess-jb-h2-face ((t (:foreground "#6ac214" :slant normal :height 1.4))))
 '(ess-jb-h3-face ((t (:foreground "#edd400" :slant normal :height 1.2))))
 '(ess-jb-hide-face ((t (:background "#2e3436" :foreground "#243436"))))
 '(ffap ((t (:background "#222244"))))
 '(file-name-shadow ((t (:foreground "grey70"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(flyspell-duplicate ((t (:bold t :foreground "Gold3" :underline t :weight bold))))
 '(flyspell-incorrect ((t (:bold t :foreground "OrangeRed" :underline t :weight bold))))
 '(font-lock-builtin-face ((t (:foreground "#729fcf"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "orange3"))))
 '(font-lock-comment-face ((t (:foreground "orange3"))))
 '(font-lock-constant-face ((t (:foreground "#8ae234"))))
 '(font-lock-doc-face ((t (:foreground "orange3"))))
 '(font-lock-function-name-face ((t (:bold t :foreground "#edd400" :weight bold))))
 '(font-lock-keyword-face ((t (:bold t :foreground "#729fcf" :weight bold))))
 '(font-lock-negation-char-face ((t (nil))))
 '(font-lock-preprocessor-face ((t (:foreground "#729fcf"))))
 '(font-lock-regexp-grouping-backslash ((t (:bold t :weight bold :underline nil))))
 '(font-lock-regexp-grouping-construct ((t (:bold t :weight bold :underline nil))))
 '(font-lock-string-face ((t (:italic t :foreground "#ad7fa8" :slant italic))))
 '(font-lock-type-face ((t (:bold t :foreground "#8ae234" :weight bold))))
 '(font-lock-variable-name-face ((t (:foreground "tomato"))))
 '(font-lock-warning-face ((t (:bold t :foreground "#f57900" :weight bold))))
 '(fringe ((t (:background "#2b303d"))))
 '(glyphless-char ((t (:height 0.6))))
 '(gnus-button ((t (:bold t :weight bold))))
 '(gnus-cite-1 ((t (:foreground "#ad7fa8"))))
 '(gnus-cite-10 ((t (:foreground "plum1"))))
 '(gnus-cite-11 ((t (:foreground "turquoise"))))
 '(gnus-cite-2 ((t (:foreground "sienna4"))))
 '(gnus-cite-3 ((t (:foreground "khaki4"))))
 '(gnus-cite-4 ((t (:foreground "PaleTurquoise4"))))
 '(gnus-cite-5 ((t (:foreground "pale green"))))
 '(gnus-cite-6 ((t (:foreground "beige"))))
 '(gnus-cite-7 ((t (:foreground "orange"))))
 '(gnus-cite-8 ((t (:foreground "magenta"))))
 '(gnus-cite-9 ((t (:foreground "violet"))))
 '(gnus-cite-attribution ((t (:italic t :slant italic))))
 '(gnus-cite-face-1 ((t (:foreground "#ad7fa8"))))
 '(gnus-cite-face-2 ((t (:foreground "sienna4"))))
 '(gnus-cite-face-3 ((t (:foreground "khaki4"))))
 '(gnus-cite-face-4 ((t (:foreground "PaleTurquoise4"))))
 '(gnus-emphasis-bold ((t (:bold t :weight bold))))
 '(gnus-emphasis-bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
 '(gnus-emphasis-highlight-words ((t (:background "black" :foreground "yellow"))))
 '(gnus-emphasis-italic ((t (:italic t :slant italic))))
 '(gnus-emphasis-strikethru ((t (:strike-through t))))
 '(gnus-emphasis-underline ((t (:underline t))))
 '(gnus-emphasis-underline-bold ((t (:bold t :underline t :weight bold))))
 '(gnus-emphasis-underline-bold-italic ((t (:italic t :bold t :underline t :slant italic :weight bold))))
 '(gnus-emphasis-underline-italic ((t (:italic t :underline t :slant italic))))
 '(gnus-face-6 ((t (:foreground "tomato"))))
 '(gnus-face-7 ((t (:foreground "#8ae234"))))
 '(gnus-face-8 ((t (:foreground "black"))))
 '(gnus-face-9 ((t (:foreground "black"))))
 '(gnus-group-mail-1 ((t (:bold t :foreground "light cyan" :weight bold))))
 '(gnus-group-mail-1-empty ((t (:foreground "light cyan"))))
 '(gnus-group-mail-2 ((t (:bold t :foreground "turquoise" :weight bold))))
 '(gnus-group-mail-2-empty ((t (:foreground "turquoise"))))
 '(gnus-group-mail-3 ((t (:bold t :foreground "#edd400" :weight bold))))
 '(gnus-group-mail-3-empty ((t (:foreground "#729fcf"))))
 '(gnus-group-mail-low ((t (:bold t :foreground "dodger blue" :weight bold))))
 '(gnus-group-mail-low-empty ((t (:foreground "dodger blue"))))
 '(gnus-group-news-1 ((t (:bold t :foreground "light cyan" :weight bold))))
 '(gnus-group-news-1-empty ((t (:foreground "light cyan"))))
 '(gnus-group-news-2 ((t (:bold t :foreground "turquoise" :weight bold))))
 '(gnus-group-news-2-empty ((t (:foreground "turquoise"))))
 '(gnus-group-news-3 ((t (:bold t :foreground "#edd400" :weight bold))))
 '(gnus-group-news-3-empty ((t (:foreground "#729fcf"))))
 '(gnus-group-news-4 ((t (:bold t :weight bold))))
 '(gnus-group-news-4-empty ((t (nil))))
 '(gnus-group-news-5 ((t (:bold t :weight bold))))
 '(gnus-group-news-5-empty ((t (nil))))
 '(gnus-group-news-6 ((t (:bold t :weight bold))))
 '(gnus-group-news-6-empty ((t (nil))))
 '(gnus-group-news-low ((t (:bold t :foreground "dodger blue" :weight bold))))
 '(gnus-group-news-low-empty ((t (:foreground "dodger blue"))))
 '(gnus-header-content ((t (:italic t :foreground "#8ae234" :slant italic))))
 '(gnus-header-from ((t (:bold t :foreground "#edd400" :weight bold))))
 '(gnus-header-name ((t (:bold t :foreground "#729fcf" :weight bold))))
 '(gnus-header-newsgroups ((t (:italic t :bold t :foreground "LightSkyBlue3" :slant italic :weight bold))))
 '(gnus-header-subject ((t (:foreground "#edd400"))))
 '(gnus-server-agent ((t (:bold t :foreground "PaleTurquoise" :weight bold))))
 '(gnus-server-closed ((t (:italic t :foreground "LightBlue" :slant italic))))
 '(gnus-server-cloud ((t (:bold t :foreground "PaleGreen" :weight bold))))
 '(gnus-server-denied ((t (:bold t :foreground "Pink" :weight bold))))
 '(gnus-server-offline ((t (:bold t :foreground "Yellow" :weight bold))))
 '(gnus-server-opened ((t (:bold t :foreground "Green1" :weight bold))))
 '(gnus-signature ((t (:italic t :foreground "dark grey" :slant italic))))
 '(gnus-splash ((t (:foreground "#cccccc"))))
 '(gnus-summary-cancelled ((t (:background "black" :foreground "yellow"))))
 '(gnus-summary-high-ancient ((t (:background "red1" :foreground "white"))))
 '(gnus-summary-high-read ((t (:background "red1" :foreground "white" :weight bold))))
 '(gnus-summary-high-ticked ((t (:background "gold" :foreground "red1" :weight bold))))
 '(gnus-summary-high-undownloaded ((t (:background "red1" :foreground "white" :weight bold :underline t))))
 '(gnus-summary-high-unread ((t (:background "red1" :foreground "white" :weight bold :underline t))))
 '(gnus-summary-low-ancient ((t (:background "forest green" :foreground "white"))))
 '(gnus-summary-low-read ((t (:background "forest green" :foreground "white" :weight bold))))
 '(gnus-summary-low-ticked ((t (:background "gold" :foreground "forest green" :weight bold))))
 '(gnus-summary-low-undownloaded ((t (:background "forest green" :foreground "white" :weight bold :underline t))))
 '(gnus-summary-low-unread ((t (:background "forest green" :foreground "white" :weight bold :underline t))))
 '(gnus-summary-normal-ancient ((t (:background "RoyalBlue" :foreground "white"))))
 '(gnus-summary-normal-read ((t (:background "RoyalBlue" :foreground "white" :weight bold))))
 '(gnus-summary-normal-ticked ((t (:background "gold" :foreground "RoyalBlue" :weight bold))))
 '(gnus-summary-normal-undownloaded ((t (:foreground "LightGray" :weight normal))))
 '(gnus-summary-normal-unread ((t (:background "RoyalBlue" :foreground "white" :weight bold :underline t))))
 '(gnus-summary-selected ((t (:background "brown4" :foreground "white"))))
 '(header-line ((t (:box (:line-width 1 :color "RoyalBlue") :background "grey20" :foreground "grey90" :box nil))))
 '(help-argument-name ((t (:italic t :slant italic :underline nil))))
 '(highlight ((t (:background "#222244"))))
 '(hl-line ((t (:background "#2222CC"))))
 '(holiday ((t (:background "chocolate4"))))
 '(ido-first-match ((t (:bold t :weight bold))))
 '(ido-incomplete-regexp ((t (:bold t :weight bold :foreground "#f57900"))))
 '(ido-indicator ((t (:background "red1" :foreground "yellow1" :width condensed))))
 '(ido-only-match ((t (:foreground "ForestGreen"))))
 '(ido-subdir ((t (:foreground "red1"))))
 '(ido-virtual ((t (:foreground "#729fcf"))))
 '(info-header-node ((t (:italic t :bold t :weight bold :slant italic :foreground "white"))))
 '(info-header-xref ((t (:foreground "#729fcf"))))
 '(info-menu-header ((t (:bold t :family "Sans Serif" :weight bold))))
 '(info-menu-star ((t (:foreground "red1"))))
 '(info-node ((t (:italic t :bold t :foreground "white" :slant italic :weight bold))))
 '(info-title-1 ((t (:bold t :weight bold :family "Sans Serif" :height 1.728))))
 '(info-title-2 ((t (:bold t :family "Sans Serif" :weight bold :height 1.44))))
 '(info-title-3 ((t (:bold t :weight bold :family "Sans Serif" :height 1.2))))
 '(info-title-4 ((t (:bold t :family "Sans Serif" :weight bold))))
 '(info-xref ((t (:foreground "#729fcf"))))
 '(info-xref-visited ((t (:foreground "#ad7fa8"))))
 '(isearch ((t (:background "#f57900" :foreground "#2e3436"))))
 '(isearch-fail ((t (:background "red4"))))
 '(iswitchb-current-match ((t (:bold t :weight bold :foreground "#edd400"))))
 '(iswitchb-invalid-regexp ((t (:bold t :weight bold :foreground "#f57900"))))
 '(iswitchb-single-match ((t (:foreground "orange3"))))
 '(iswitchb-virtual-matches ((t (:foreground "#729fcf"))))
 '(italic ((t (:italic t :underline nil :slant italic))))
 '(jabber-activity-face ((t (:bold t :weight bold :foreground "#edd400"))))
 '(jabber-activity-personal-face ((t (:italic t :bold t :foreground "#ad7fa8" :slant italic :weight bold))))
 '(jabber-chat-error ((t (:bold t :foreground "red" :weight bold))))
 '(jabber-chat-prompt-foreign ((t (:bold t :foreground "#edd400" :weight bold))))
 '(jabber-chat-prompt-local ((t (:italic t :bold t :slant italic :foreground "#ad7fa8" :weight bold))))
 '(jabber-chat-prompt-system ((t (:bold t :foreground "orange3" :weight bold))))
 '(jabber-chat-text-foreign ((t (nil))))
 '(jabber-chat-text-local ((t (nil))))
 '(jabber-rare-time-face ((t (:bold t :foreground "#edd400" :weight bold))))
 '(jabber-roster-user-away ((t (:bold t :weight bold :foreground "#729fcf"))))
 '(jabber-roster-user-chatty ((t (:bold t :foreground "#8ae234" :weight bold))))
 '(jabber-roster-user-dnd ((t (:foreground "orange3"))))
 '(jabber-roster-user-error ((t (:bold t :weight bold :foreground "#f57900"))))
 '(jabber-roster-user-offline ((t (:foreground "gray40"))))
 '(jabber-roster-user-online ((t (:bold t :foreground "#729fcf" :weight bold))))
 '(jabber-roster-user-xa ((t (:foreground "orange3"))))
 '(jabber-title-large ((t (:bold t :weight bold :height 1.728))))
 '(jabber-title-medium ((t (:bold t :weight bold :height 1.44))))
 '(jabber-title-small ((t (:bold t :weight bold :height 1.2))))
 '(jiralib-comment-face ((t (:background "gray23"))))
 '(jiralib-comment-header-face ((t (:bold t :weight bold))))
 '(jiralib-issue-info-face ((t (:background "yellow4" :foreground "black"))))
 '(jiralib-issue-info-header-face ((t (:bold t :foreground "black" :background "yellow4" :weight bold))))
 '(jiralib-issue-summary-face ((t (:bold t :weight bold))))
 '(jiralib-link-filter-face ((t (:underline t))))
 '(jiralib-link-issue-face ((t (:underline t))))
 '(jiralib-link-project-face ((t (:underline t))))
 '(lazy-highlight ((t (:background "#e9b96e" :foreground "#2e3436"))))
 '(link ((t (:foreground "dodger blue" :underline t))))
 '(link-visited ((t (:underline t :foreground "violet"))))
 '(log-edit-header ((t (:bold t :weight bold :foreground "#729fcf"))))
 '(log-edit-summary ((t (:bold t :weight bold :foreground "#edd400"))))
 '(log-edit-unknown-header ((t (:foreground "orange3"))))
 '(lt-hi-blue ((t (:background "blue" :foreground "black"))))
 '(lt-hi-green ((t (:background "green" :foreground "black"))))
 '(lt-hi-orange ((t (:background "orange" :foreground "black"))))
 '(lt-hi-pink ((t (:background "pink" :foreground "black"))))
 '(lt-hi-red ((t (:background "red" :foreground "black"))))
 '(lt-hi-yellow ((t (:background "yellow" :foreground "black"))))
 '(magit-branch ((t (:foreground "#edd400"))))
 '(magit-diff-add ((t (:foreground "#729fcf"))))
 '(magit-diff-del ((t (:foreground "orange3"))))
 '(magit-diff-file-header ((t (:foreground "RoyalBlue1"))))
 '(magit-diff-hunk-header ((t (:foreground "#fbde2d"))))
 '(magit-diff-merge-current ((t (:foreground "#729fcf"))))
 '(magit-diff-merge-diff3-separator ((t (:foreground "#729fcf"))))
 '(magit-diff-merge-proposed ((t (:foreground "#729fcf"))))
 '(magit-diff-merge-separator ((t (:foreground "#729fcf"))))
 '(magit-diff-none ((t (nil))))
 '(magit-header ((t (:foreground "#edd400"))))
 '(magit-item-highlight ((t (:bold t :inverse-video nil :weight extra-bold))))
 '(magit-item-mark ((t (:background "SkyBlue4"))))
 '(magit-log-author ((t (:foreground "tomato"))))
 '(magit-log-author-date-cutoff ((t (:bold t :foreground "tomato" :weight bold))))
 '(magit-log-date ((t (nil))))
 '(magit-log-graph ((t (:foreground "grey80"))))
 '(magit-log-head-label-bisect-bad ((t (:background "IndianRed1" :foreground "IndianRed4" :box 1))))
 '(magit-log-head-label-bisect-good ((t (:background "light green" :foreground "dark olive green" :box 1))))
 '(magit-log-head-label-default ((t (:background "Grey50" :box 1))))
 '(magit-log-head-label-local ((t (:background "Grey13" :foreground "LightSkyBlue1" :box 1))))
 '(magit-log-head-label-patches ((t (:background "IndianRed1" :foreground "IndianRed4" :box 1))))
 '(magit-log-head-label-remote ((t (:background "Grey11" :foreground "DarkSeaGreen2" :box 1))))
 '(magit-log-head-label-tags ((t (:background "LemonChiffon1" :foreground "goldenrod4" :box 1))))
 '(magit-log-message ((t (nil))))
 '(magit-log-sha1 ((t (:foreground "tomato"))))
 '(magit-section-title ((t (:foreground "#edd400"))))
 '(magit-tag ((t (:foreground "#edd400"))))
 '(magit-valid-signature ((t (:bold t :weight bold :foreground "PaleTurquoise"))))
 '(magit-whitespace-warning-face ((t (:background "red1"))))
 '(makefile-makepp-perl ((t (:background "DarkBlue"))))
 '(makefile-shell ((t (nil))))
 '(makefile-space ((t (:background "hotpink"))))
 '(makefile-targets ((t (:bold t :weight bold :foreground "#edd400"))))
 '(match ((t (:bold t :background "#e9b96e" :foreground "#2e3436" :weight bold))))
 '(menu ((t (nil))))
 '(message-cited-text ((t (:foreground "#edd400"))))
 '(message-header-cc ((t (:foreground "white"))))
 '(message-header-name ((t (:foreground "tomato"))))
 '(message-header-newsgroups ((t (:italic t :bold t :foreground "LightSkyBlue3" :slant italic :weight bold))))
 '(message-header-other ((t (:foreground "LightSkyBlue3"))))
 '(message-header-subject ((t (:foreground "white"))))
 '(message-header-to ((t (:foreground "white"))))
 '(message-header-xheader ((t (:foreground "DodgerBlue3"))))
 '(message-mml ((t (:foreground "MediumSpringGreen"))))
 '(message-separator ((t (:foreground "LightSkyBlue1"))))
 '(minibuffer-prompt ((t (:bold t :foreground "#729fcf" :weight bold))))
 '(mm-command-output ((t (:foreground "ForestGreen"))))
 '(mm-uu-extract ((t (:background "dark green" :foreground "light yellow"))))
 '(mode-line ((t (:background "#2b303d" :foreground "#bbbbbc" :box (:line-width 1 :color "RoyalBlue")))))
 '(mode-line-buffer-id ((t (:bold t :foreground "orange" :weight bold))))
 '(mode-line-emphasis ((t (:bold t :weight bold))))
 '(mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
 '(mode-line-inactive ((t (:background "#2b303d" :foreground "#bbbbbc"))))
 '(mouse ((t (:background "#8ae234"))))
 '(muse-bad-link ((t (:bold t :foreground "coral" :underline "coral" :weight bold))))
 '(muse-emphasis-1 ((t (:italic t :slant italic))))
 '(muse-emphasis-2 ((t (:bold t :weight bold))))
 '(muse-emphasis-3 ((t (:italic t :bold t :slant italic :weight bold))))
 '(muse-header-1 ((t (:bold t :foreground "dodger blue" :weight bold :height 1.5))))
 '(muse-header-2 ((t (:bold t :foreground "#edd400" :weight bold :height 1.2))))
 '(muse-header-3 ((t (:bold t :foreground "#6ac214" :weight bold :height 1.0))))
 '(muse-header-4 ((t (:bold t :foreground "tomato" :weight bold :height 1.0))))
 '(muse-header-5 ((t (:bold t :weight bold :height 1.0 :family "Sans Serif"))))
 '(muse-link ((t (:bold t :foreground "cyan" :underline "cyan" :weight bold))))
 '(muse-verbatim ((t (:foreground "tan1"))))
 '(next-error ((t (:background "RoyalBlue"))))
 '(nobreak-space ((t (:foreground "cyan" :underline t))))
 '(notmuch-crypto-decryption ((t (:background "purple" :foreground "black"))))
 '(notmuch-crypto-part-header ((t (:foreground "blue"))))
 '(notmuch-crypto-signature-bad ((t (:background "red" :foreground "black"))))
 '(notmuch-crypto-signature-good ((t (:background "green" :foreground "black"))))
 '(notmuch-crypto-signature-good-key ((t (:background "orange" :foreground "black"))))
 '(notmuch-crypto-signature-unknown ((t (:background "red" :foreground "black"))))
 '(notmuch-hello-logo-background ((t (:background "#5f5f5f"))))
 '(notmuch-message-summary-face ((t (:background "#303030"))))
 '(notmuch-search-count ((t (:family "DejaVu Sans Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#FFFFFF" :background "black" :stipple nil :height 75))))
 '(notmuch-search-date ((t (:family "DejaVu Sans Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#FFFFFF" :background "black" :stipple nil :height 75))))
 '(notmuch-search-matching-authors ((t (:family "DejaVu Sans Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#FFFFFF" :background "black" :stipple nil :height 75))))
 '(notmuch-search-non-matching-authors ((t (:foreground "grey30"))))
 '(notmuch-search-subject ((t (:family "DejaVu Sans Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#FFFFFF" :background "black" :stipple nil :height 75))))
 '(notmuch-tag-face ((t (:foreground "OliveDrab1"))))
 '(notmuch-tree-match-author-face ((t (:foreground "OliveDrab1"))))
 '(notmuch-tree-match-date-face ((t (:family "DejaVu Sans Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#FFFFFF" :background "black" :stipple nil :height 75))))
 '(notmuch-tree-match-subject-face ((t (:family "DejaVu Sans Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#FFFFFF" :background "black" :stipple nil :height 75))))
 '(notmuch-tree-match-tag-face ((t (:foreground "OliveDrab1"))))
 '(notmuch-tree-match-tree-face ((t (:family "DejaVu Sans Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#FFFFFF" :background "black" :stipple nil :height 75))))
 '(notmuch-tree-no-match-author-face ((t (:foreground "gray"))))
 '(notmuch-tree-no-match-date-face ((t (:foreground "gray"))))
 '(notmuch-tree-no-match-subject-face ((t (:foreground "gray"))))
 '(notmuch-tree-no-match-tag-face ((t (:foreground "gray"))))
 '(notmuch-tree-no-match-tree-face ((t (:foreground "gray"))))
 '(offlineimap-error-face ((t (:bold t :foreground "red" :weight bold))))
 '(offlineimap-msg-acct-face ((t (:foreground "purple"))))
 '(offlineimap-msg-addingflags-face ((t (:foreground "yellow"))))
 '(offlineimap-msg-connecting-face ((t (:foreground "gray"))))
 '(offlineimap-msg-copyingmessage-face ((t (:foreground "orange"))))
 '(offlineimap-msg-deletingflags-face ((t (:foreground "pink"))))
 '(offlineimap-msg-deletingmessage-face ((t (:foreground "red"))))
 '(offlineimap-msg-deletingmessages-face ((t (:foreground "red"))))
 '(offlineimap-msg-loadmessagelist-face ((t (:foreground "green"))))
 '(offlineimap-msg-skippingfolder-face ((t (:foreground "cyan"))))
 '(offlineimap-msg-syncfolders-face ((t (:foreground "blue"))))
 '(offlineimap-msg-syncingfolders-face ((t (:foreground "cyan"))))
 '(offlineimap-msg-syncingmessages-face ((t (:foreground "blue"))))
 '(org-agenda-calendar-event ((t (:family "DejaVu Sans Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#FFFFFF" :background "black" :stipple nil :height 75))))
 '(org-agenda-calendar-sexp ((t (:family "DejaVu Sans Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#FFFFFF" :background "black" :stipple nil :height 75))))
 '(org-agenda-clocking ((t (:background "SkyBlue4"))))
 '(org-agenda-column-dateline ((t (:family "DejaVu Sans Mono" :weight normal :slant normal :underline nil :strike-through nil :background "grey30" :height 75))))
 '(org-agenda-current-time ((t (:foreground "LightGoldenrod"))))
 '(org-agenda-date ((t (:foreground "#6ac214"))))
 '(org-agenda-date-today ((t (:bold t :foreground "#edd400" :weight bold))))
 '(org-agenda-date-weekend ((t (:foreground "dodger blue" :weight normal))))
 '(org-agenda-diary ((t (:family "DejaVu Sans Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#FFFFFF" :background "black" :stipple nil :height 75))))
 '(org-agenda-dimmed-todo-face ((t (:foreground "grey50"))))
 '(org-agenda-done ((t (:foreground "PaleGreen"))))
 '(org-agenda-filter-category ((t (:box (:line-width 1 :color "RoyalBlue") :foreground "#bbbbbc" :background "#2b303d"))))
 '(org-agenda-filter-tags ((t (:box (:line-width 1 :color "RoyalBlue") :foreground "#bbbbbc" :background "#2b303d"))))
 '(org-agenda-restriction-lock ((t (:background "skyblue4"))))
 '(org-agenda-structure ((t (:bold t :foreground "tomato" :weight bold))))
 '(org-archived ((t (:foreground "grey70"))))
 '(org-block ((t (:foreground "#bbbbbc"))))
 '(org-block-background ((t (nil))))
 '(org-block-begin-line ((t (:foreground "orange3"))))
 '(org-block-end-line ((t (:foreground "orange3"))))
 '(org-checkbox ((t (:bold t :weight bold :underline nil))))
 '(org-checkbox-statistics-done ((t (:bold t :weight bold :foreground "ForestGreen"))))
 '(org-checkbox-statistics-todo ((t (:bold t :weight bold :foreground "Red"))))
 '(org-clock-overlay ((t (:background "SkyBlue4"))))
 '(org-code ((t (:foreground "grey70"))))
 '(org-column ((t (:background "grey30" :strike-through nil :underline nil :slant normal :weight normal :height 75 :family "DejaVu Sans Mono"))))
 '(org-column-title ((t (:bold t :background "grey30" :underline t :weight bold))))
 '(org-date ((t (:foreground "magenta3" :underline t))))
 '(org-date-selected ((t (:background "Pink"))))
 '(org-default ((t (:family "DejaVu Sans Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#FFFFFF" :background "black" :stipple nil :height 75))))
 '(org-document-info ((t (:foreground "pale turquoise"))))
 '(org-document-info-keyword ((t (:foreground "grey70"))))
 '(org-document-title ((t (:bold t :foreground "pale turquoise" :weight bold))))
 '(org-done ((t (:bold t :foreground "ForestGreen" :weight bold))))
 '(org-drawer ((t (:foreground "LightSkyBlue"))))
 '(org-ellipsis ((t (:foreground "LightGoldenrod" :underline t))))
 '(org-footnote ((t (:foreground "magenta3" :underline t))))
 '(org-formula ((t (:foreground "chocolate1"))))
 '(org-headline-done ((t (:foreground "LightSalmon"))))
 '(org-hide ((t (:foreground "#2e3436"))))
 '(org-latex-and-export-specials ((t (:foreground "burlywood"))))
 '(org-level-1 ((t (:bold t :foreground "dodger blue" :weight bold :height 1.5))))
 '(org-level-2 ((t (:bold t :foreground "#edd400" :weight bold :height 1.2))))
 '(org-level-3 ((t (:bold t :foreground "#6ac214" :weight bold :height 1.0))))
 '(org-level-4 ((t (:bold t :foreground "tomato" :weight bold :height 1.0))))
 '(org-level-5 ((t (:bold t :foreground "#8ae234" :weight bold))))
 '(org-level-6 ((t (:foreground "#8ae234"))))
 '(org-level-7 ((t (:foreground "#729fcf"))))
 '(org-level-8 ((t (:italic t :foreground "#ad7fa8" :slant italic))))
 '(org-link ((t (:foreground "skyblue2" :underline t))))
 '(org-list-dt ((t (:bold t :weight bold))))
 '(org-meta-line ((t (:foreground "orange3"))))
 '(org-mode-line-clock ((t (:box (:line-width 1 :color "RoyalBlue") :foreground "#bbbbbc" :background "#2b303d"))))
 '(org-mode-line-clock-overrun ((t (:box (:line-width 1 :color "RoyalBlue") :foreground "#bbbbbc" :background "red"))))
 '(org-property-value ((t (nil))))
 '(org-quote ((t (:italic t :foreground "#bbbbbc" :slant italic))))
 '(org-scheduled ((t (:foreground "PaleGreen"))))
 '(org-scheduled-previously ((t (:foreground "chocolate1"))))
 '(org-scheduled-today ((t (:foreground "PaleGreen"))))
 '(org-sexp-date ((t (:foreground "Cyan"))))
 '(org-special-keyword ((t (:foreground "brown"))))
 '(org-table ((t (:foreground "LightSkyBlue"))))
 '(org-tag ((t (:bold t :weight bold))))
 '(org-target ((t (:underline t))))
 '(org-time-grid ((t (:foreground "LightGoldenrod"))))
 '(org-todo ((t (:bold t :foreground "Red" :weight bold))))
 '(org-upcoming-deadline ((t (:foreground "chocolate1"))))
 '(org-verbatim ((t (:italic t :foreground "#eeeeec" :underline t :slant italic))))
 '(org-verse ((t (:italic t :foreground "#bbbbbc" :slant italic))))
 '(org-warning ((t (:bold t :weight bold :foreground "#f57900"))))
 '(outline-1 ((t (:bold t :weight bold :foreground "#edd400"))))
 '(outline-2 ((t (:foreground "tomato"))))
 '(outline-3 ((t (:bold t :weight bold :foreground "#729fcf"))))
 '(outline-4 ((t (:foreground "orange3"))))
 '(outline-5 ((t (:bold t :weight bold :foreground "#8ae234"))))
 '(outline-6 ((t (:foreground "#8ae234"))))
 '(outline-7 ((t (:foreground "#729fcf"))))
 '(outline-8 ((t (:italic t :slant italic :foreground "#ad7fa8"))))
 '(purple-chat-received-face ((t (:bold t :foreground "SteelBlue1" :weight bold))))
 '(purple-chat-wrote-face ((t (:bold t :foreground "salmon" :weight bold))))
 '(query-replace ((t (:foreground "#2e3436" :background "#f57900"))))
 '(region ((t (:background "RoyalBlue"))))
 '(scroll-bar ((t (nil))))
 '(secondary-selection ((t (:background "SkyBlue4"))))
 '(sgml-namespace ((t (:foreground "#729fcf"))))
 '(sh-escaped-newline ((t (:italic t :slant italic :foreground "#ad7fa8"))))
 '(sh-heredoc ((t (:bold t :foreground "yellow1" :weight bold))))
 '(sh-quoted-exec ((t (:foreground "salmon"))))
 '(shadow ((t (:foreground "grey70"))))
 '(show-paren-match ((t (:background "#73d216" :foreground "#2e3436"))))
 '(show-paren-mismatch ((t (:background "#ad7fa8" :foreground "#2e3436"))))
 '(shr-link ((t (:underline t :foreground "dodger blue"))))
 '(shr-strike-through ((t (:strike-through t))))
 '(simple-wiki-bold-face ((t (:bold t :weight bold))))
 '(simple-wiki-code-face ((t (:background "grey15"))))
 '(simple-wiki-emph-face ((t (:italic t :slant italic))))
 '(simple-wiki-heading-1-face ((t (:bold t :weight bold :family "Sans Serif" :height 1.728))))
 '(simple-wiki-heading-2-face ((t (:bold t :family "Sans Serif" :weight bold :height 1.44))))
 '(simple-wiki-heading-3-face ((t (:bold t :weight bold :family "Sans Serif" :height 1.2))))
 '(simple-wiki-heading-4-face ((t (:bold t :family "Sans Serif" :weight bold))))
 '(simple-wiki-heading-5-face ((t (:bold t :family "Sans Serif" :weight bold))))
 '(simple-wiki-heading-6-face ((t (:bold t :family "Sans Serif" :weight bold))))
 '(simple-wiki-italic-face ((t (:italic t :slant italic))))
 '(simple-wiki-local-link-face ((t (:bold t :foreground "skyblue3" :weight bold))))
 '(simple-wiki-nowiki-face ((t (:foreground "LightGoldenRod2"))))
 '(simple-wiki-smiley-face ((t (:bold t :foreground "gold" :weight bold))))
 '(simple-wiki-strike-face ((t (:strike-through t))))
 '(simple-wiki-strong-emph-face ((t (:italic t :bold t :slant italic :weight bold))))
 '(simple-wiki-strong-face ((t (:bold t :weight bold))))
 '(simple-wiki-teletype-face ((t (:background "grey15"))))
 '(simple-wiki-underline-face ((t (:underline t))))
 '(smerge-base ((t (:background "#888833"))))
 '(smerge-markers ((t (:background "grey30"))))
 '(smerge-mine ((t (:background "#553333"))))
 '(smerge-other ((t (:background "#335533"))))
 '(smerge-refined-added ((t (:background "#22aa22"))))
 '(smerge-refined-change ((t (nil))))
 '(smerge-refined-removed ((t (:background "#aa2222"))))
 '(status-activity-face ((t (:bold t :family "Sans Serif" :foreground "orange" :weight bold :width ultra-expanded))))
 '(status-battery-charged-face ((t (:family "Sans Serif" :foreground "green" :width ultra-expanded))))
 '(status-battery-charging-face ((t (:family "Sans Serif" :foreground "RoyalBlue" :width ultra-expanded))))
 '(status-battery-discharging-face ((t (:family "Sans Serif" :foreground "brown1" :width ultra-expanded))))
 '(status-date-face ((t (:family "Sans Serif" :foreground "RoyalBlue" :width ultra-expanded))))
 '(status-gnus-face ((t (:bold t :family "Sans Serif" :foreground "yellow" :weight bold :width ultra-expanded))))
 '(status-project-manager-face ((t (:bold t :family "Sans Serif" :foreground "RoyalBlue" :weight bold :width ultra-expanded))))
 '(status-purple-face ((t (:bold t :family "Sans Serif" :foreground "lightblue" :weight bold :width ultra-expanded))))
 '(status-time-face ((t (:bold t :family "Sans Serif" :foreground "RoyalBlue" :weight bold :width ultra-expanded))))
 '(success ((t (:bold t :foreground "Green1" :weight bold))))
 '(term ((t (:family "DejaVu Sans Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#FFFFFF" :background "black" :stipple nil :height 75))))
 '(term-bold ((t (:bold t :weight bold))))
 '(term-color-black ((t (:background "black" :foreground "black"))))
 '(term-color-blue ((t (:background "blue2" :foreground "blue2"))))
 '(term-color-cyan ((t (:background "cyan3" :foreground "cyan3"))))
 '(term-color-green ((t (:background "green3" :foreground "green3"))))
 '(term-color-magenta ((t (:background "magenta3" :foreground "magenta3"))))
 '(term-color-red ((t (:background "red3" :foreground "red3"))))
 '(term-color-white ((t (:background "white" :foreground "white"))))
 '(term-color-yellow ((t (:background "yellow3" :foreground "yellow3"))))
 '(term-underline ((t (:underline t))))
 '(tool-bar ((t (:background "grey75" :foreground "black" :box (:line-width 1 :style released-button)))))
 '(tool-tips ((t (:family "Sans Serif" :background "lightyellow" :foreground "black"))))
 '(tooltip ((t (:family "Sans Serif" :background "lightyellow" :foreground "black"))))
 '(trailing-whitespace ((t (:background "red1"))))
 '(underline ((t (:underline t))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(vertical-border ((t (nil))))
 '(w3m-anchor-face ((t (:foreground "green" :underline t))))
 '(w3m-arrived-anchor-face ((t (:foreground "purple1" :underline t))))
 '(w3m-bold-face ((t (:bold t :weight bold :height 1.2))))
 '(w3m-current-anchor-face ((t (:bold t :foreground "green" :underline t :weight bold))))
 '(w3m-form-button-face ((t (:background "lightgrey" :foreground "black"))))
 '(w3m-form-button-mouse-face ((t (:background "orange"))))
 '(w3m-form-button-pressed-face ((t (:background "yellow"))))
 '(w3m-form-face ((t (:foreground "green4" :underline t))))
 '(w3m-header-line-location-content ((t (:foreground "lightsteelblue" :height 3))))
 '(w3m-header-line-location-content-face ((t (:foreground "lightsteelblue" :height 1.5))))
 '(w3m-header-line-location-title ((t (:foreground "gainsboro" :height 3))))
 '(w3m-header-line-location-title-face ((t (:foreground "gainsboro" :height 1.5))))
 '(w3m-history-current-url-face ((t (:background "SkyBlue4" :foreground "LightSkyBlue"))))
 '(w3m-image-face ((t (:foreground "PaleGreen"))))
 '(w3m-strike-through-face ((t (:strike-through t))))
 '(w3m-tab-background-face ((t (:background "rgb:21/36/4B"))))
 '(w3m-tab-selected-face ((t (:background "Gray85" :foreground "black" :box (:line-width 1 :style nil)))))
 '(w3m-tab-selected-retrieving-face ((t (:background "Gray85" :foreground "white" :box (:line-width -1 :style nil)))))
 '(w3m-tab-unselected-face ((t (:background "Gray70" :foreground "Gray20" :box (:line-width 1 :style nil)))))
 '(w3m-tab-unselected-retrieving-face ((t (:background "Gray50" :foreground "white" :box (:line-width -1 :style nil)))))
 '(w3m-underline-face ((t (:underline t))))
 '(warning ((t (:bold t :foreground "DarkOrange" :weight bold))))
 '(widget-button ((t (:bold t :weight bold))))
 '(widget-button-pressed ((t (:foreground "red1"))))
 '(widget-documentation ((t (:foreground "lime green"))))
 '(widget-field ((t (:background "gray30" :foreground "orange"))))
 '(widget-inactive ((t (:foreground "grey70"))))
 '(widget-mouse-face ((t (:bold t :background "brown4" :foreground "white" :weight bold))))
 '(widget-single-line-field ((t (:background "gray30" :foreground "orange")))))

(provide-theme 'j2m)

;; Local Variables:
;; no-byte-compile: t
;; End:
